# -*- coding: utf-8 -*-
"""Copy of read_audio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qLJ67wIyUMN4nxyOtcVYAtRFNRE1ZLlP

download a sample audio file into your local environment
"""

# Import gdown module to download files from google drive
import gdown
#drive url: https://drive.google.com/file/d/1j2nosyvsIJFviYeSKjrlCldzqdUNscTj/view?usp=sharing
download_url = 'https://drive.google.com/uc?id=1j2nosyvsIJFviYeSKjrlCldzqdUNscTj'
file_location = 'star_wars_3_seconds.wav'
# Download the file from drive to your local machine
gdown.download(download_url, file_location, quiet=False)

"""Read the file"""

import wave
audio_file = wave.open(file_location, 'r')
print(audio_file)

"""Convert to bytes"""

sampling_rate = audio_file.getframerate()
print('Sampling rate: ', sampling_rate)
audio_wav_bytes = audio_file.readframes(-1)
print(audio_wav_bytes)

"""Convert bytes to integers"""

import numpy as np
# Convert buffer to int16 using NumPy                                                                                 
audio_as_np_int16 = np.frombuffer(audio_wav_bytes, dtype=np.int16)

"""Plot the numbers"""

# View the file
import matplotlib.pyplot as plt
plt.figure(1)
plt.xlabel('Sample Number')
plt.ylabel('Amplitude') 
plt.title("Star Wars 3 Seconds")
plt.plot(audio_as_np_int16)
plt.show()

"""View a part of the file"""

# View the file
import matplotlib.pyplot as plt
plt.figure(1)
plt.xlabel('Sample Number')
plt.ylabel('Amplitude') 
plt.title("Star Wars Audio - 2000 Samples")
plt.plot(audio_as_np_int16[10000:12000])
plt.show()

"""Listen to the audio"""

# Import IPython module to play the audio in the notebook
import IPython
# Play the downloaded audio file
IPython.display.Audio(file_location, autoplay=True)